# Generated by Django 5.0.6 on 2024-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.CharField(max_length=45)),
                ('range_end', models.CharField(max_length=45)),
                ('as_number', models.IntegerField()),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('as_description', models.TextField()),
            ],
            options={
                'db_table': 'as_info',
            },
        ),
    ]
