# Generated by Django 5.0.6 on 2024-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinfo',
            name='range_end',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='asinfo',
            name='range_start',
            field=models.GenericIPAddressField(),
        ),
    ]
